// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rabbitmq.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDefaultUserArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDefaultUserArgs Empty = new GetDefaultUserArgs();

    @Import(name="username")
    private @Nullable Output<String> username;

    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private GetDefaultUserArgs() {}

    private GetDefaultUserArgs(GetDefaultUserArgs $) {
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDefaultUserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDefaultUserArgs $;

        public Builder() {
            $ = new GetDefaultUserArgs();
        }

        public Builder(GetDefaultUserArgs defaults) {
            $ = new GetDefaultUserArgs(Objects.requireNonNull(defaults));
        }

        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        public Builder username(String username) {
            return username(Output.of(username));
        }

        public GetDefaultUserArgs build() {
            return $;
        }
    }

}
