// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rabbitmq.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.rabbitmq.inputs.OperatorPolicyPolicyArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OperatorPolicyState extends com.pulumi.resources.ResourceArgs {

    public static final OperatorPolicyState Empty = new OperatorPolicyState();

    /**
     * The name of the operator policy.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the operator policy.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The settings of the operator policy. The structure is
     * described below.
     * 
     */
    @Import(name="policy")
    private @Nullable Output<OperatorPolicyPolicyArgs> policy;

    /**
     * @return The settings of the operator policy. The structure is
     * described below.
     * 
     */
    public Optional<Output<OperatorPolicyPolicyArgs>> policy() {
        return Optional.ofNullable(this.policy);
    }

    /**
     * The vhost to create the resource in.
     * 
     */
    @Import(name="vhost")
    private @Nullable Output<String> vhost;

    /**
     * @return The vhost to create the resource in.
     * 
     */
    public Optional<Output<String>> vhost() {
        return Optional.ofNullable(this.vhost);
    }

    private OperatorPolicyState() {}

    private OperatorPolicyState(OperatorPolicyState $) {
        this.name = $.name;
        this.policy = $.policy;
        this.vhost = $.vhost;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OperatorPolicyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OperatorPolicyState $;

        public Builder() {
            $ = new OperatorPolicyState();
        }

        public Builder(OperatorPolicyState defaults) {
            $ = new OperatorPolicyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the operator policy.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the operator policy.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param policy The settings of the operator policy. The structure is
         * described below.
         * 
         * @return builder
         * 
         */
        public Builder policy(@Nullable Output<OperatorPolicyPolicyArgs> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy The settings of the operator policy. The structure is
         * described below.
         * 
         * @return builder
         * 
         */
        public Builder policy(OperatorPolicyPolicyArgs policy) {
            return policy(Output.of(policy));
        }

        /**
         * @param vhost The vhost to create the resource in.
         * 
         * @return builder
         * 
         */
        public Builder vhost(@Nullable Output<String> vhost) {
            $.vhost = vhost;
            return this;
        }

        /**
         * @param vhost The vhost to create the resource in.
         * 
         * @return builder
         * 
         */
        public Builder vhost(String vhost) {
            return vhost(Output.of(vhost));
        }

        public OperatorPolicyState build() {
            return $;
        }
    }

}
