// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rabbitmq.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class PermissionsPermissionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final PermissionsPermissionsArgs Empty = new PermissionsPermissionsArgs();

    /**
     * The &#34;configure&#34; ACL.
     * 
     */
    @Import(name="configure", required=true)
    private Output<String> configure;

    /**
     * @return The &#34;configure&#34; ACL.
     * 
     */
    public Output<String> configure() {
        return this.configure;
    }

    /**
     * The &#34;read&#34; ACL.
     * 
     */
    @Import(name="read", required=true)
    private Output<String> read;

    /**
     * @return The &#34;read&#34; ACL.
     * 
     */
    public Output<String> read() {
        return this.read;
    }

    /**
     * The &#34;write&#34; ACL.
     * 
     */
    @Import(name="write", required=true)
    private Output<String> write;

    /**
     * @return The &#34;write&#34; ACL.
     * 
     */
    public Output<String> write() {
        return this.write;
    }

    private PermissionsPermissionsArgs() {}

    private PermissionsPermissionsArgs(PermissionsPermissionsArgs $) {
        this.configure = $.configure;
        this.read = $.read;
        this.write = $.write;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PermissionsPermissionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PermissionsPermissionsArgs $;

        public Builder() {
            $ = new PermissionsPermissionsArgs();
        }

        public Builder(PermissionsPermissionsArgs defaults) {
            $ = new PermissionsPermissionsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param configure The &#34;configure&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder configure(Output<String> configure) {
            $.configure = configure;
            return this;
        }

        /**
         * @param configure The &#34;configure&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder configure(String configure) {
            return configure(Output.of(configure));
        }

        /**
         * @param read The &#34;read&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder read(Output<String> read) {
            $.read = read;
            return this;
        }

        /**
         * @param read The &#34;read&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder read(String read) {
            return read(Output.of(read));
        }

        /**
         * @param write The &#34;write&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder write(Output<String> write) {
            $.write = write;
            return this;
        }

        /**
         * @param write The &#34;write&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder write(String write) {
            return write(Output.of(write));
        }

        public PermissionsPermissionsArgs build() {
            if ($.configure == null) {
                throw new MissingRequiredPropertyException("PermissionsPermissionsArgs", "configure");
            }
            if ($.read == null) {
                throw new MissingRequiredPropertyException("PermissionsPermissionsArgs", "read");
            }
            if ($.write == null) {
                throw new MissingRequiredPropertyException("PermissionsPermissionsArgs", "write");
            }
            return $;
        }
    }

}
