// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rabbitmq.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.rabbitmq.inputs.ShovelInfoArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ShovelState extends com.pulumi.resources.ResourceArgs {

    public static final ShovelState Empty = new ShovelState();

    /**
     * The settings of the dynamic shovel. The structure is
     * described below.
     * 
     */
    @Import(name="info")
    private @Nullable Output<ShovelInfoArgs> info;

    /**
     * @return The settings of the dynamic shovel. The structure is
     * described below.
     * 
     */
    public Optional<Output<ShovelInfoArgs>> info() {
        return Optional.ofNullable(this.info);
    }

    /**
     * The shovel name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The shovel name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The vhost to create the resource in.
     * 
     */
    @Import(name="vhost")
    private @Nullable Output<String> vhost;

    /**
     * @return The vhost to create the resource in.
     * 
     */
    public Optional<Output<String>> vhost() {
        return Optional.ofNullable(this.vhost);
    }

    private ShovelState() {}

    private ShovelState(ShovelState $) {
        this.info = $.info;
        this.name = $.name;
        this.vhost = $.vhost;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ShovelState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ShovelState $;

        public Builder() {
            $ = new ShovelState();
        }

        public Builder(ShovelState defaults) {
            $ = new ShovelState(Objects.requireNonNull(defaults));
        }

        /**
         * @param info The settings of the dynamic shovel. The structure is
         * described below.
         * 
         * @return builder
         * 
         */
        public Builder info(@Nullable Output<ShovelInfoArgs> info) {
            $.info = info;
            return this;
        }

        /**
         * @param info The settings of the dynamic shovel. The structure is
         * described below.
         * 
         * @return builder
         * 
         */
        public Builder info(ShovelInfoArgs info) {
            return info(Output.of(info));
        }

        /**
         * @param name The shovel name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The shovel name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param vhost The vhost to create the resource in.
         * 
         * @return builder
         * 
         */
        public Builder vhost(@Nullable Output<String> vhost) {
            $.vhost = vhost;
            return this;
        }

        /**
         * @param vhost The vhost to create the resource in.
         * 
         * @return builder
         * 
         */
        public Builder vhost(String vhost) {
            return vhost(Output.of(vhost));
        }

        public ShovelState build() {
            return $;
        }
    }

}
