// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rabbitmq.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class TopicPermissionsPermissionArgs extends com.pulumi.resources.ResourceArgs {

    public static final TopicPermissionsPermissionArgs Empty = new TopicPermissionsPermissionArgs();

    /**
     * The exchange to set the permissions for.
     * 
     */
    @Import(name="exchange", required=true)
    private Output<String> exchange;

    /**
     * @return The exchange to set the permissions for.
     * 
     */
    public Output<String> exchange() {
        return this.exchange;
    }

    /**
     * The &#34;read&#34; ACL.
     * 
     */
    @Import(name="read", required=true)
    private Output<String> read;

    /**
     * @return The &#34;read&#34; ACL.
     * 
     */
    public Output<String> read() {
        return this.read;
    }

    /**
     * The &#34;write&#34; ACL.
     * 
     */
    @Import(name="write", required=true)
    private Output<String> write;

    /**
     * @return The &#34;write&#34; ACL.
     * 
     */
    public Output<String> write() {
        return this.write;
    }

    private TopicPermissionsPermissionArgs() {}

    private TopicPermissionsPermissionArgs(TopicPermissionsPermissionArgs $) {
        this.exchange = $.exchange;
        this.read = $.read;
        this.write = $.write;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TopicPermissionsPermissionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TopicPermissionsPermissionArgs $;

        public Builder() {
            $ = new TopicPermissionsPermissionArgs();
        }

        public Builder(TopicPermissionsPermissionArgs defaults) {
            $ = new TopicPermissionsPermissionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param exchange The exchange to set the permissions for.
         * 
         * @return builder
         * 
         */
        public Builder exchange(Output<String> exchange) {
            $.exchange = exchange;
            return this;
        }

        /**
         * @param exchange The exchange to set the permissions for.
         * 
         * @return builder
         * 
         */
        public Builder exchange(String exchange) {
            return exchange(Output.of(exchange));
        }

        /**
         * @param read The &#34;read&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder read(Output<String> read) {
            $.read = read;
            return this;
        }

        /**
         * @param read The &#34;read&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder read(String read) {
            return read(Output.of(read));
        }

        /**
         * @param write The &#34;write&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder write(Output<String> write) {
            $.write = write;
            return this;
        }

        /**
         * @param write The &#34;write&#34; ACL.
         * 
         * @return builder
         * 
         */
        public Builder write(String write) {
            return write(Output.of(write));
        }

        public TopicPermissionsPermissionArgs build() {
            if ($.exchange == null) {
                throw new MissingRequiredPropertyException("TopicPermissionsPermissionArgs", "exchange");
            }
            if ($.read == null) {
                throw new MissingRequiredPropertyException("TopicPermissionsPermissionArgs", "read");
            }
            if ($.write == null) {
                throw new MissingRequiredPropertyException("TopicPermissionsPermissionArgs", "write");
            }
            return $;
        }
    }

}
