provider: rabbitmq
docker: true
major-version: 3
makeTemplate: bridged
team: ecosystem
javaGenVersion: v0.9.7
pulumiConvert: 1
registryDocs: true
plugins:
    - name: terraform
      version: "1.0.16"
      kind: converter
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
