// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.RabbitMQ
{
    public static class GetDefaultUser
    {
        public static Task<GetDefaultUserResult> InvokeAsync(GetDefaultUserArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDefaultUserResult>("rabbitmq:index/getDefaultUser:getDefaultUser", args ?? new GetDefaultUserArgs(), options.WithDefaults());

        public static Output<GetDefaultUserResult> Invoke(GetDefaultUserInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDefaultUserResult>("rabbitmq:index/getDefaultUser:getDefaultUser", args ?? new GetDefaultUserInvokeArgs(), options.WithDefaults());

        public static Output<GetDefaultUserResult> Invoke(GetDefaultUserInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDefaultUserResult>("rabbitmq:index/getDefaultUser:getDefaultUser", args ?? new GetDefaultUserInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDefaultUserArgs : global::Pulumi.InvokeArgs
    {
        [Input("username")]
        public string? Username { get; set; }

        public GetDefaultUserArgs()
        {
        }
        public static new GetDefaultUserArgs Empty => new GetDefaultUserArgs();
    }

    public sealed class GetDefaultUserInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("username")]
        public Input<string>? Username { get; set; }

        public GetDefaultUserInvokeArgs()
        {
        }
        public static new GetDefaultUserInvokeArgs Empty => new GetDefaultUserInvokeArgs();
    }


    [OutputType]
    public sealed class GetDefaultUserResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Username;

        [OutputConstructor]
        private GetDefaultUserResult(
            string id,

            string? username)
        {
            Id = id;
            Username = username;
        }
    }
}
