// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.RabbitMQ
{
    public static class GetVHost
    {
        public static Task<GetVHostResult> InvokeAsync(GetVHostArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetVHostResult>("rabbitmq:index/getVHost:getVHost", args ?? new GetVHostArgs(), options.WithDefaults());

        public static Output<GetVHostResult> Invoke(GetVHostInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetVHostResult>("rabbitmq:index/getVHost:getVHost", args ?? new GetVHostInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVHostArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetVHostArgs()
        {
        }
        public static new GetVHostArgs Empty => new GetVHostArgs();
    }

    public sealed class GetVHostInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetVHostInvokeArgs()
        {
        }
        public static new GetVHostInvokeArgs Empty => new GetVHostInvokeArgs();
    }


    [OutputType]
    public sealed class GetVHostResult
    {
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetVHostResult(
            string id,

            string name)
        {
            Id = id;
            Name = name;
        }
    }
}
