// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.RabbitMQ
{
    /// <summary>
    /// The ``rabbitmq.VHost`` resource creates and manages a vhost.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using RabbitMQ = Pulumi.RabbitMQ;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var myVhost = new RabbitMQ.VHost("my_vhost", new()
    ///     {
    ///         Name = "my_vhost",
    ///         Description = "My Vhost",
    ///         DefaultQueueType = "quorum",
    ///         MaxConnections = "200",
    ///         MaxQueues = "100",
    ///         Tracing = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Vhosts can be imported using the `Name`, e.g.
    /// 
    /// ```sh
    /// $ pulumi import rabbitmq:index/vHost:VHost my_vhost my_vhost
    /// ```
    /// </summary>
    [RabbitMQResourceType("rabbitmq:index/vHost:VHost")]
    public partial class VHost : global::Pulumi.CustomResource
    {
        /// <summary>
        /// default queue type for new queues
        /// </summary>
        [Output("defaultQueueType")]
        public Output<string?> DefaultQueueType { get; private set; } = null!;

        /// <summary>
        /// A friendly description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Maximum number of concurrent client connections to the vhost
        /// </summary>
        [Output("maxConnections")]
        public Output<string?> MaxConnections { get; private set; } = null!;

        /// <summary>
        /// Maximum number of queues that can be created on the vhost
        /// </summary>
        [Output("maxQueues")]
        public Output<string?> MaxQueues { get; private set; } = null!;

        /// <summary>
        /// The name of the vhost.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("tracing")]
        public Output<bool?> Tracing { get; private set; } = null!;


        /// <summary>
        /// Create a VHost resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VHost(string name, VHostArgs? args = null, CustomResourceOptions? options = null)
            : base("rabbitmq:index/vHost:VHost", name, args ?? new VHostArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VHost(string name, Input<string> id, VHostState? state = null, CustomResourceOptions? options = null)
            : base("rabbitmq:index/vHost:VHost", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VHost resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VHost Get(string name, Input<string> id, VHostState? state = null, CustomResourceOptions? options = null)
        {
            return new VHost(name, id, state, options);
        }
    }

    public sealed class VHostArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// default queue type for new queues
        /// </summary>
        [Input("defaultQueueType")]
        public Input<string>? DefaultQueueType { get; set; }

        /// <summary>
        /// A friendly description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Maximum number of concurrent client connections to the vhost
        /// </summary>
        [Input("maxConnections")]
        public Input<string>? MaxConnections { get; set; }

        /// <summary>
        /// Maximum number of queues that can be created on the vhost
        /// </summary>
        [Input("maxQueues")]
        public Input<string>? MaxQueues { get; set; }

        /// <summary>
        /// The name of the vhost.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tracing")]
        public Input<bool>? Tracing { get; set; }

        public VHostArgs()
        {
        }
        public static new VHostArgs Empty => new VHostArgs();
    }

    public sealed class VHostState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// default queue type for new queues
        /// </summary>
        [Input("defaultQueueType")]
        public Input<string>? DefaultQueueType { get; set; }

        /// <summary>
        /// A friendly description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Maximum number of concurrent client connections to the vhost
        /// </summary>
        [Input("maxConnections")]
        public Input<string>? MaxConnections { get; set; }

        /// <summary>
        /// Maximum number of queues that can be created on the vhost
        /// </summary>
        [Input("maxQueues")]
        public Input<string>? MaxQueues { get; set; }

        /// <summary>
        /// The name of the vhost.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tracing")]
        public Input<bool>? Tracing { get; set; }

        public VHostState()
        {
        }
        public static new VHostState Empty => new VHostState();
    }
}
