// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rabbitmq.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class PermissionsPermissions {
    /**
     * @return The &#34;configure&#34; ACL.
     * 
     */
    private String configure;
    /**
     * @return The &#34;read&#34; ACL.
     * 
     */
    private String read;
    /**
     * @return The &#34;write&#34; ACL.
     * 
     */
    private String write;

    private PermissionsPermissions() {}
    /**
     * @return The &#34;configure&#34; ACL.
     * 
     */
    public String configure() {
        return this.configure;
    }
    /**
     * @return The &#34;read&#34; ACL.
     * 
     */
    public String read() {
        return this.read;
    }
    /**
     * @return The &#34;write&#34; ACL.
     * 
     */
    public String write() {
        return this.write;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PermissionsPermissions defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String configure;
        private String read;
        private String write;
        public Builder() {}
        public Builder(PermissionsPermissions defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.configure = defaults.configure;
    	      this.read = defaults.read;
    	      this.write = defaults.write;
        }

        @CustomType.Setter
        public Builder configure(String configure) {
            if (configure == null) {
              throw new MissingRequiredPropertyException("PermissionsPermissions", "configure");
            }
            this.configure = configure;
            return this;
        }
        @CustomType.Setter
        public Builder read(String read) {
            if (read == null) {
              throw new MissingRequiredPropertyException("PermissionsPermissions", "read");
            }
            this.read = read;
            return this;
        }
        @CustomType.Setter
        public Builder write(String write) {
            if (write == null) {
              throw new MissingRequiredPropertyException("PermissionsPermissions", "write");
            }
            this.write = write;
            return this;
        }
        public PermissionsPermissions build() {
            final var _resultValue = new PermissionsPermissions();
            _resultValue.configure = configure;
            _resultValue.read = read;
            _resultValue.write = write;
            return _resultValue;
        }
    }
}
