// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package rabbitmq

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "rabbitmq:index/binding:Binding":
		r, err = NewBinding(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/exchange:Exchange":
		r, err = NewExchange(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/federationUpstream:FederationUpstream":
		r, err = NewFederationUpstream(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/permissions:Permissions":
		r, err = NewPermissions(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/policy:Policy":
		r, err = NewPolicy(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/queue:Queue":
		r, err = NewQueue(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/shovel:Shovel":
		r, err = NewShovel(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/topicPermissions:TopicPermissions":
		r, err = NewTopicPermissions(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/user:User":
		r, err = NewUser(ctx, name, nil, pulumi.URN_(urn))
	case "rabbitmq:index/vHost:VHost":
		r, err = NewVHost(ctx, name, nil, pulumi.URN_(urn))
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:rabbitmq" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	return NewProvider(ctx, name, nil, pulumi.URN_(urn))
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/binding",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/exchange",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/federationUpstream",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/permissions",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/policy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/queue",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/shovel",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/topicPermissions",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"rabbitmq",
		"index/vHost",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"rabbitmq",
		&pkg{version},
	)
}
