// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rabbitmq;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.rabbitmq.QueueArgs;
import com.pulumi.rabbitmq.Utilities;
import com.pulumi.rabbitmq.inputs.QueueState;
import com.pulumi.rabbitmq.outputs.QueueSettings;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * The ``rabbitmq.Queue`` resource creates and manages a queue.
 * 
 * ## Example Usage
 * ### Basic Example
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.rabbitmq.VHost;
 * import com.pulumi.rabbitmq.Permissions;
 * import com.pulumi.rabbitmq.PermissionsArgs;
 * import com.pulumi.rabbitmq.inputs.PermissionsPermissionsArgs;
 * import com.pulumi.rabbitmq.Queue;
 * import com.pulumi.rabbitmq.QueueArgs;
 * import com.pulumi.rabbitmq.inputs.QueueSettingsArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var testVHost = new VHost(&#34;testVHost&#34;);
 * 
 *         var guest = new Permissions(&#34;guest&#34;, PermissionsArgs.builder()        
 *             .user(&#34;guest&#34;)
 *             .vhost(testVHost.name())
 *             .permissions(PermissionsPermissionsArgs.builder()
 *                 .configure(&#34;.*&#34;)
 *                 .write(&#34;.*&#34;)
 *                 .read(&#34;.*&#34;)
 *                 .build())
 *             .build());
 * 
 *         var testQueue = new Queue(&#34;testQueue&#34;, QueueArgs.builder()        
 *             .vhost(guest.vhost())
 *             .settings(QueueSettingsArgs.builder()
 *                 .durable(false)
 *                 .autoDelete(true)
 *                 .arguments(Map.of(&#34;x-queue-type&#34;, &#34;quorum&#34;))
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * ```
 * ### Example With JSON Arguments
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.rabbitmq.VHost;
 * import com.pulumi.rabbitmq.Permissions;
 * import com.pulumi.rabbitmq.PermissionsArgs;
 * import com.pulumi.rabbitmq.inputs.PermissionsPermissionsArgs;
 * import com.pulumi.rabbitmq.Queue;
 * import com.pulumi.rabbitmq.QueueArgs;
 * import com.pulumi.rabbitmq.inputs.QueueSettingsArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         final var config = ctx.config();
 *         final var arguments = config.get(&#34;arguments&#34;).orElse(&#34;&#34;&#34;
 * {
 *   &#34;x-message-ttl&#34;: 5000
 * }
 * 
 *         &#34;&#34;&#34;);
 *         var testVHost = new VHost(&#34;testVHost&#34;);
 * 
 *         var guest = new Permissions(&#34;guest&#34;, PermissionsArgs.builder()        
 *             .permissions(PermissionsPermissionsArgs.builder()
 *                 .configure(&#34;.*&#34;)
 *                 .read(&#34;.*&#34;)
 *                 .write(&#34;.*&#34;)
 *                 .build())
 *             .user(&#34;guest&#34;)
 *             .vhost(testVHost.name())
 *             .build());
 * 
 *         var testQueue = new Queue(&#34;testQueue&#34;, QueueArgs.builder()        
 *             .settings(QueueSettingsArgs.builder()
 *                 .argumentsJson(arguments)
 *                 .autoDelete(true)
 *                 .durable(false)
 *                 .build())
 *             .vhost(guest.vhost())
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * Queues can be imported using the `id` which is composed of `name@vhost`. E.g.
 * 
 * ```sh
 *  $ pulumi import rabbitmq:index/queue:Queue test name@vhost
 * ```
 * 
 */
@ResourceType(type="rabbitmq:index/queue:Queue")
public class Queue extends com.pulumi.resources.CustomResource {
    /**
     * The name of the queue.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return The name of the queue.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The settings of the queue. The structure is
     * described below.
     * 
     */
    @Export(name="settings", type=QueueSettings.class, parameters={})
    private Output<QueueSettings> settings;

    /**
     * @return The settings of the queue. The structure is
     * described below.
     * 
     */
    public Output<QueueSettings> settings() {
        return this.settings;
    }
    /**
     * The vhost to create the resource in.
     * 
     */
    @Export(name="vhost", type=String.class, parameters={})
    private Output</* @Nullable */ String> vhost;

    /**
     * @return The vhost to create the resource in.
     * 
     */
    public Output<Optional<String>> vhost() {
        return Codegen.optional(this.vhost);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Queue(String name) {
        this(name, QueueArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Queue(String name, QueueArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Queue(String name, QueueArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("rabbitmq:index/queue:Queue", name, args == null ? QueueArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Queue(String name, Output<String> id, @Nullable QueueState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("rabbitmq:index/queue:Queue", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Queue get(String name, Output<String> id, @Nullable QueueState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Queue(name, id, state, options);
    }
}
