// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.RabbitMQ.Outputs
{

    [OutputType]
    public sealed class GetExchangeSettingResult
    {
        public readonly ImmutableDictionary<string, string>? Arguments;
        public readonly bool? AutoDelete;
        public readonly bool? Durable;
        public readonly string Type;

        [OutputConstructor]
        private GetExchangeSettingResult(
            ImmutableDictionary<string, string>? arguments,

            bool? autoDelete,

            bool? durable,

            string type)
        {
            Arguments = arguments;
            AutoDelete = autoDelete;
            Durable = durable;
            Type = type;
        }
    }
}
