// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.RabbitMQ.Outputs
{

    [OutputType]
    public sealed class PermissionsPermissions
    {
        /// <summary>
        /// The "configure" ACL.
        /// </summary>
        public readonly string Configure;
        /// <summary>
        /// The "read" ACL.
        /// </summary>
        public readonly string Read;
        /// <summary>
        /// The "write" ACL.
        /// </summary>
        public readonly string Write;

        [OutputConstructor]
        private PermissionsPermissions(
            string configure,

            string read,

            string write)
        {
            Configure = configure;
            Read = read;
            Write = write;
        }
    }
}
