// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.RabbitMQ.Inputs
{

    public sealed class PolicyPolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Can either be "exchanges", "queues", or "all".
        /// </summary>
        [Input("applyTo", required: true)]
        public Input<string> ApplyTo { get; set; } = null!;

        [Input("definition", required: true)]
        private InputMap<object>? _definition;

        /// <summary>
        /// Key/value pairs of the policy definition. See the
        /// RabbitMQ documentation for definition references and examples.
        /// </summary>
        public InputMap<object> Definition
        {
            get => _definition ?? (_definition = new InputMap<object>());
            set => _definition = value;
        }

        /// <summary>
        /// A pattern to match an exchange or queue name.
        /// </summary>
        [Input("pattern", required: true)]
        public Input<string> Pattern { get; set; } = null!;

        /// <summary>
        /// The policy with the greater priority is applied first.
        /// </summary>
        [Input("priority", required: true)]
        public Input<int> Priority { get; set; } = null!;

        public PolicyPolicyArgs()
        {
        }
        public static new PolicyPolicyArgs Empty => new PolicyPolicyArgs();
    }
}
