// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.RabbitMQ.Inputs
{

    public sealed class ShovelInfoGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ackMode")]
        public Input<string>? AckMode { get; set; }

        [Input("addForwardHeaders")]
        public Input<bool>? AddForwardHeaders { get; set; }

        [Input("deleteAfter")]
        public Input<string>? DeleteAfter { get; set; }

        [Input("destinationAddForwardHeaders")]
        public Input<bool>? DestinationAddForwardHeaders { get; set; }

        [Input("destinationAddTimestampHeader")]
        public Input<bool>? DestinationAddTimestampHeader { get; set; }

        [Input("destinationAddress")]
        public Input<string>? DestinationAddress { get; set; }

        [Input("destinationApplicationProperties")]
        public Input<string>? DestinationApplicationProperties { get; set; }

        [Input("destinationExchange")]
        public Input<string>? DestinationExchange { get; set; }

        [Input("destinationExchangeKey")]
        public Input<string>? DestinationExchangeKey { get; set; }

        [Input("destinationProperties")]
        public Input<string>? DestinationProperties { get; set; }

        [Input("destinationProtocol")]
        public Input<string>? DestinationProtocol { get; set; }

        [Input("destinationPublishProperties")]
        public Input<string>? DestinationPublishProperties { get; set; }

        [Input("destinationQueue")]
        public Input<string>? DestinationQueue { get; set; }

        [Input("destinationUri", required: true)]
        public Input<string> DestinationUri { get; set; } = null!;

        [Input("prefetchCount")]
        public Input<int>? PrefetchCount { get; set; }

        [Input("reconnectDelay")]
        public Input<int>? ReconnectDelay { get; set; }

        [Input("sourceAddress")]
        public Input<string>? SourceAddress { get; set; }

        [Input("sourceDeleteAfter")]
        public Input<string>? SourceDeleteAfter { get; set; }

        [Input("sourceExchange")]
        public Input<string>? SourceExchange { get; set; }

        [Input("sourceExchangeKey")]
        public Input<string>? SourceExchangeKey { get; set; }

        [Input("sourcePrefetchCount")]
        public Input<int>? SourcePrefetchCount { get; set; }

        [Input("sourceProtocol")]
        public Input<string>? SourceProtocol { get; set; }

        [Input("sourceQueue")]
        public Input<string>? SourceQueue { get; set; }

        [Input("sourceUri", required: true)]
        public Input<string> SourceUri { get; set; } = null!;

        public ShovelInfoGetArgs()
        {
        }
        public static new ShovelInfoGetArgs Empty => new ShovelInfoGetArgs();
    }
}
