// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getExchange(args: GetExchangeArgs, opts?: pulumi.InvokeOptions): Promise<GetExchangeResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("rabbitmq:index/getExchange:getExchange", {
        "name": args.name,
        "vhost": args.vhost,
    }, opts);
}

/**
 * A collection of arguments for invoking getExchange.
 */
export interface GetExchangeArgs {
    name: string;
    vhost?: string;
}

/**
 * A collection of values returned by getExchange.
 */
export interface GetExchangeResult {
    readonly id: string;
    readonly name: string;
    readonly settings: outputs.GetExchangeSetting[];
    readonly vhost?: string;
}

export function getExchangeOutput(args: GetExchangeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetExchangeResult> {
    return pulumi.output(args).apply(a => getExchange(a, opts))
}

/**
 * A collection of arguments for invoking getExchange.
 */
export interface GetExchangeOutputArgs {
    name: pulumi.Input<string>;
    vhost?: pulumi.Input<string>;
}
