// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVHost(args: GetVHostArgs, opts?: pulumi.InvokeOptions): Promise<GetVHostResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("rabbitmq:index/getVHost:getVHost", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getVHost.
 */
export interface GetVHostArgs {
    name: string;
}

/**
 * A collection of values returned by getVHost.
 */
export interface GetVHostResult {
    readonly id: string;
    readonly name: string;
}

export function getVHostOutput(args: GetVHostOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVHostResult> {
    return pulumi.output(args).apply(a => getVHost(a, opts))
}

/**
 * A collection of arguments for invoking getVHost.
 */
export interface GetVHostOutputArgs {
    name: pulumi.Input<string>;
}
